backend:
  name: github
  repo: "adilarshidin/websites"
  branch: master

media_folder: "inmaculada_concepcion/content/images"

collections:
  - name: "schedule"
    label: "Horarios"
    files:
      - name: "masses"
        label: "Misas"
        file: "inmaculada_concepcion/content/schedule/masses.md"
        fields:
          - { label: "Contenido", name: "body", widget: "markdown" }
